---
- name: Install traceroute on all hosts
  hosts: all
  gather_facts: true
  become: true

  tasks:
  - name: Install traceroute
    yum:
      name: traceroute
      state: present


- name: "Сonfiguring the inetrouter"
  hosts: inetrouter
  gather_facts: true
  roles:
    - inetrouter
  become: true


- name: "Сonfiguring routers"
  hosts: routers
  gather_facts: true
  roles:
    - routers
  become: true

  
- name: "Сonfiguring servers"
  hosts: servers
  gather_facts: true
  roles:
    - servers
  become: true



